[package]
name = "crayon"
version = "0.2.0"
authors = [ "Jingkai Mao <oammix@gmail.com>" ]

description = "An experimental entity-component-based multithread game engine."
repository = "https://github.com/shawnscode/crayon"
documentation = "http://docs.rs/crayon"
readme = "README.md"
license = "Apache-2.0"

keywords = ["ecs", "entity-component", "game-dev", "multithread"]
categories = ["game-engines", "multimedia"]

[badges]
travis-ci = { repository = "shawnscode/crayon", branch = "master" }

[workspace]
members = [ "crayon-examples", "modules/imgui" ]

[dependencies]
libc = "0.2.36"
gl = "0.9.0"
glutin = "0.12.0"
cgmath = "0.16.0"
error-chain = "0.11.0"

two-lock-queue = "0.1.1"
zip = "0.3.0"

[dev-dependencies]
rand = "0.4.2"
rayon = "0.9.0"
approx = "0.1.1"