[package]
name = "crayon"
version = "0.0.6"
authors = [ "Jingkai Mao <oammix@gmail.com>" ]

description = "An experimental entity-component-based multithread game engine."
repository = "https://github.com/shawnscode/crayon"
documentation = "http://docs.rs/crayon"
readme = "README.md"
license = "Apache-2.0"

keywords = ["ecs", "entity-component", "game-dev", "multithread"]
categories = ["game-engines", "multimedia"]

[badges]
travis-ci = { repository = "shawnscode/crayon", branch = "master" }

[workspace]
members = [ "crayon-examples", "modules/canvas", "modules/imgui" ]

[dependencies]
libc = "0.2.33"
gl = "0.6.5"
glutin = "0.10.1"

lazy_static = "1.0.0"
error-chain = "0.11.0"

rayon = "0.9.0"
serde = "1.0.22"
serde_derive = "1.0.22"

cgmath = "0.15.0"
bit-set = "0.4.0"
two-lock-queue = "0.1.1"
zip = "0.2.6"

[dev-dependencies]
rand = "0.3.18"