[Workflow.ProjectSettings]
# List all the resource folders that will be included in the playable package.
resources = [ "resources" ]

[Workflow.ImportSettings]
# Type table used when crayon-cli import new resources.
bytes = [ ".bytes", ".lua" ]
textures = [ ".png", ".tga", ".bmp" ]
atlases = [ ".atlas" ]

[Runtime.EngineSettings]
# Set the minimal frames per second. If fps goes lower than this,
# time will appear to slow. This is useful for some subsystems required
# strict minimal time step per frame, such like collision checks.
min_fps = 20

# Set the maximum frames per second. The engine will sleep if fps is
# higher than this for less resource(e.g. power) consumptions.
max_fps = 60

# Set how many frames to average for timestep smoothing.
time_smooth_step = 10

[Runtime.WindowSettings]
title = "Hello, Crayon!"
width = 640
height = 320